### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find "libnative-lib.so"

### ISSUE THREAD

**Issue by baudouxbenjamin** [massoudss/waveformSeekBar#10] opened 2020-10-05 10:23 UTC
Hi,

I got the following error when using your librarie:

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/base.apk"],nativeLibraryDirectories=[/data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/lib/x86, /data/app/appli.speaky.com.debug-HBTfQoCC8f4atW-yZnZPGQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libnative-lib.so"

I'm using the `2.0.0`version.

**Comment by lincollincol** [comment] 2020-10-05 10:50
Duplicate of #11

**Closed** 2021-01-08 10:29 UTC
